org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=ApothicAttributes
modName=Apothic Attributes
modGroup=dev.shadowsoffire
modid=apothic_attributes
author=Shadows_of_Fire
desc=A library mod providing Attributes and related things.
version=2.10.0

# Dependencies
mcVersion=1.21.1
javaVersion=21
forgeVersion=21.1.235
parchmentVersion=2024.11.17-1.21.1
jeiVersion=19.21.2.313
jadeVersion=15.10.2
curiosVersion=9.5.1+1.21.1
placeboVersion=9.9.0

# Mixins
mixin=true
mixinVersion=0.8.7

# Publishing=
# Dependency lists are comma-separated. Each entry is "slug" (both platforms) or "curseforgeSlug|modrinthSlug".
requiredDeps=placebo
optionalDeps=curios
#incompatibleDeps=
releaseType=release
modLoaders=NeoForge
curseforgeProjectId=898963
modrinthProjectId=DGaH8Rh0

# Tests
enableTests=false
