org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=ApothicAttributes
modName=Apothic Attributes
modGroup=dev.shadowsoffire
modid=apothic_attributes
author=Shadows_of_Fire
desc=A library mod providing Attributes and related things.
version=2.8.0

# Dependencies
mcVersion=1.21.1
javaVersion=21
forgeVersion=21.1.144
parchmentVersion=2024.07.28-1.21
jeiVersion=19.8.4.113
jadeVersion=15.1.6
curiosVersion=9.3.1+1.21.1
placeboVersion=9.8.0
#topVersion=1.20.0-9.0.0-1
#patchouliVersion=1.19.2-76

# Mixins
mixin=true
mixinVersion=0.8.7

# Publishing=
requiredDeps=placebo
optionalDeps=curios
#incompatibleDeps=
releaseType=release
modLoaders=NeoForge
curseforgeProjectId=898963
#modrinthProjectId=

# Tests
enableTests=false
