modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="apothic_attributes"

version="3.0.1"

displayName="Apothic Attributes"

authors="Shadows_of_Fire"

description='''A library mod providing Attributes and related things.'''

[[mixins]]
config="apothic_attributes.mixins.json"

[[dependencies.apothic_attributes]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apothic_attributes]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.70-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apothic_attributes]]
    modId="placebo"
    type="required"
    versionRange="[10.0.0,)"
    ordering="AFTER"
    side="BOTH"
